### ISSUE TITLE
Incorrent upload-url returned when creating configuration version

### ISSUE THREAD

**Issue by philek** [MatthewJohn/terrarun#5]
The URL should be a full absolute URL. Currently only the path is returned.

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terra/terrarun/-/issues/157
gitlab-issue-id:157

**Comment by MatthewJohn** [comment]
Addressed in https://gitlab.dockstudios.co.uk/pub/terra/terrarun/-/merge_requests/69
